version: '3.4'

services:
  reactfrontend:
    image: reactfrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173
    command: npm run dev